## 异常

#### 15.3.1处理异常的基本方法

> 在异常机制不使用的情况下，处理异常的基本方法之一是使用库cstdlib的Abort()函数。

> 这个函数向标准错误流cerr发送abnormal program termination（程序异常终止信息），然后终止程序。

#### 15.3.2返回错误码来终止异常

> 使用这种方法处理异常显得更灵活。

> 最后一种方法是使用一个专门存储结果的全局变量来判断。

#### 15.3.3异常机制

> 异常处理机制由try、throw和catch组成。

> try负责引发异常，throw负责返回异常特征，catch负责捕获异常特征并处理异常。

**语法**

```c++
try{
    异常测试1;
    异常测试2;
    ...
}						//如果没有引发异常，则catch块会被跳过
```

```c++
throw ...;		//一般特征可以是一个字符串，或者一个异常类（结果集）
```

```c++
catch (参数类型声明)
{
    处理语句;
}
```

> 一般而言，throw语句往往在try所测试的函数中出现。一旦throw被执行，则沿函数调用序列后退，直到找到包含try块的函数，并沿着try块继续执行。（而不是返回到调用函数）

**案例**

```c++
#include<iostream>

double hmean(double a, double b);

int main()
{
    double x,y,z;
    std::cout<<"Enter two numbers: ";
    while(std::cin>>x>>y)
    {
        try {
            z=hmean(x,y);
        }
        catch (const char* s)
        {
            std::cout<<s<<std::endl;
            std::cout<<"Enter a new pair of numbers: ";
            continue;
        }
        std::cout<<" Harmonic mean of "<<x<<" and "<<y
            <<" is "<< z<< std::endl;
        std::cout<<"Enter next set of numbers <q to quit>: ";
	}
    std::cout<< "Bye!\n";
    return 0;
}

double hmean(double a, double b)
{
    if(a == -b)
    {
        throw "bad hmean() arguments: a = -b not allowed";		//如果执行这步，函数直接返回
	}
    return 2.0*a*b/(a+b);
}
```

---

#### 15.3.4将对象用于异常类型（异常类）

> 引发异常的函数传递一个对象，以此区分不同函数在不同情况下的异常。对象携带的信息也有助于处理异常。

**案例**

```c++
class bad_hmean
{
private:
    double v1;
    double v2;
public:
    bad_hmean(int a = 0, int b = 0) : v1(a), v2(b){}
    void mesg()
}
```

```c++
if(a == -b)
    throw bad_hmean(a,b);	//返回一个bad_hmean对象类型的异常（创建了匿名bad_hmean对象）
```

#### 15.3.5异常规范

> 略

#### 15.3.6栈解退

> 函数多级调用是以栈的形式存储，其内部参数作为自动变量同样使用栈存储。
>
> 在throw被执行，是沿函数调用序列后退，直到找到包含try块的函数，并沿着try块继续执行。而如果在多级调用中，将连续释放多个函数，并调用可能存在的类析构函数语句。

#### 15.3.7其它异常特性

> 1.throw语句将控制权向上返回给第一个try-catch组合

> 2.引发异常时，编译器总是创建一个临时拷贝，即使异常规范或catch块中指定引用。

代码中使用引用的原因：**基类引用能与派生类对象匹配**

---

由于这个特性，如果想捕获特定的派生类，应当从最后的派生向基类依次编写catch。

```c++
catch(derived_class3 & aim){...}
catch(derived_class2 & aim){...}
catch(derived_class1 & aim){...}
catch(base_class & aim){...}
//如果先捕获基类，则会把派生类一并捕获
```

#### 15.3.8 exception类

##### 1.exception类介绍

> `exception`库提供exception类，可以作为其它异常类的基类来使用。
>
> 其中，`what`虚成员函数，返回一个异常提示字符串。可以在派生类中重新定义它。

```c++
#include<exception>
class bad_hmean : public std::exception		//作用域解析符不能少
{
public:
    const char* what() {return "bad arguments to hmean()";}
    ...
};
class bad_gmean :public std::exception
{
public:
    const char* what() {return "bad arguments to gmean()";}
    ...
};
```

对于不同的异常类，如果想一次处理，可以都以exception为基类，在catch时使用基类引用。

```c++
try{
    ...
}
catch(exception & e)
{
    cout<<e.what()<<endl;
}
```

##### 2.基于exception的异常类

###### 2.1stdexcept异常类

> 在头文件`stdexcept`中定义了`logic_error`和`runtime_error`类。

```c++
class logic_error : public exception	//定义区域本身在std作用域内
{
    public:
    explict logic_error (const string & what_arg);
    ...
}
//runtime_error同理
```

**构造函数用于接收一个异常string来给what()函数返回字符串**

`logic_error`类的派生类

```c++
domain_error;
invalid_error;
lengh_error;
out_of_bounds;
```

`runtime_error`类的派生类

```c++
range_error;
overflow_error;
underflow_error;
```

---

###### 2.2bad_alloc异常和new

> 对于使用new引发的内存分配问题，C++使用bad_alloc异常来处理。这个类定义在头文件new中。

```c++
#include<iostream>
#include<new>
#include<cstdlib>
using namespace std;

struct Big{
    double struff[200];
}

int main()
{
    Big* pb;
    try{
        cout<<"Trying to get a big block of memory:\n";
        pb = new Big[10000];
        cout<<"Got past the new request:\n";
    }
    catch(bad_alloc & ba)
    {
        cout<<"Catch the exception!\n";
        cout<<ba.what()<<endl;
        exit(EXIT_FALLURE);
	}
    cout<<"Memery successfully allocated\n";
    pd[0].stuff[0]<<endl;
    delete [] pb;
    return 0;
}
```

---

###### 2.3空指针和new

> 一般new失败会抛出异常。
>
> C++提供了一种在失败时，抑制异常而是返回空指针的new

```c++
int *pi = new (std::nothrow) int;
```

#### 15.3.9异常、类和继承

> 在类中定义异常类，并可以在派生类中定义异常的派生类

#### 15.3.10异常何时会迷失方向

> 在函数中new一个空间，如果之后在delete之前出现了异常，则会直接跳出函数，丢失指向内存的指针，从而导致无法释放内存，也就是内存泄漏。

**注：对象会自动调用析构函数被释放，但new不会**

